import { UnitConfig, UnitId } from '../types';

export const UNIT_CONFIGS: Record<UnitId, UnitConfig> = {
  Small: {
    id: 'Small',
    nameKo: '아기 펭귄',
    nameJa: '赤ちゃんペンギン',
    role: 'Swarm',
    roleKo: '빠른 출격 & 지원',
    roleJa: '速攻・軽量突撃',
    cost: 1,
    maxHp: 80,
    moveSpeed: 80,
    reloadSeconds: 1.1,
    attackPower: 15,
    attackRange: 150,
    ballMoveSpeed: 1.35,
    ballArcHeight: 45,
    ballRadius: 7,
    descriptionKo: '비용 1로 빠르게 출격하여 눈뭉치를 던지고 전선을 지원합니다.',
    descriptionJa: 'コスト1で手軽に出撃！小さな雪玉を素早く投げて前線をかき乱す。',
    color: '#00AEEF',
    accentColor: '#F59E0B',
    size: 26,
  },
  Speed: {
    id: 'Speed',
    nameKo: '스피드 펭귄',
    nameJa: 'スピードペンギン',
    role: 'Speed',
    roleKo: '초고속 돌격',
    roleJa: '高速特攻',
    cost: 3,
    maxHp: 150,
    moveSpeed: 140,
    reloadSeconds: 1.2,
    attackPower: 30,
    attackRange: 130,
    ballMoveSpeed: 1.5,
    ballArcHeight: 40,
    ballRadius: 8,
    descriptionKo: '바람처럼 빠르게 달려나가 적의 원거리 펭귄과 진영을 기습합니다.',
    descriptionJa: '風のように走り抜ける！足の速さを活かして敵の背後や拠点を奇襲。',
    color: '#00AEEF',
    accentColor: '#F59E0B',
    size: 30,
  },
  Shooter: {
    id: 'Shooter',
    nameKo: '스나이퍼 펭귄',
    nameJa: 'シューターペンギン',
    role: 'Shooter',
    roleKo: '초원거리 저격',
    roleJa: '遠距離狙撃',
    cost: 5,
    maxHp: 180,
    moveSpeed: 55,
    reloadSeconds: 1.8,
    attackPower: 45,
    attackRange: 320,
    ballMoveSpeed: 1.1,
    ballArcHeight: 90,
    ballRadius: 9,
    descriptionKo: '높은 포물선을 그리는 눈뭉치로 안전한 거리에서 적군과 이글루를 폭격합니다.',
    descriptionJa: '遠くから高弾道の雪玉を放つスナイパー。後方からの頼れる援護役。',
    color: '#00AEEF',
    accentColor: '#F59E0B',
    size: 33,
  },
  Tank: {
    id: 'Tank',
    nameKo: '탱커 펭귄',
    nameJa: 'タンクペンギン',
    role: 'Tank',
    roleKo: '전선 유지 & 넉백',
    roleJa: '前線維持・重撃',
    cost: 7,
    maxHp: 480,
    moveSpeed: 42,
    reloadSeconds: 2.2,
    attackPower: 65,
    attackRange: 160,
    ballMoveSpeed: 0.95,
    ballArcHeight: 65,
    ballRadius: 14,
    splashRadius: 36,
    descriptionKo: '높은 체력으로 적의 눈뭉치를 막아내고 묵직한 대형 눈덩이를 굴립니다.',
    descriptionJa: '高いHPで敵の攻撃を受け止めつつ、重たい巨大雪玉で相手をノックバック！',
    color: '#00AEEF',
    accentColor: '#F59E0B',
    size: 38,
  },
  King: {
    id: 'King',
    nameKo: '킹 펭귄',
    nameJa: 'キングペンギン',
    role: 'Boss',
    roleKo: '황금 왕관 & 광역 폭격',
    roleJa: '最強の王・範囲攻撃',
    cost: 10,
    maxHp: 950,
    moveSpeed: 34,
    reloadSeconds: 2.6,
    attackPower: 110,
    attackRange: 250,
    ballMoveSpeed: 0.9,
    ballArcHeight: 115,
    ballRadius: 20,
    splashRadius: 70,
    descriptionKo: '황금빛 볏을 세운 눈싸움의 제왕! 전장을 초토화하는 거대 폭발 눈덩이를 투척합니다.',
    descriptionJa: '黄金の王冠を戴く雪合戦の王者！着弾時に大爆発を起こす超特大雪玉を放つ！',
    color: '#00AEEF',
    accentColor: '#F59E0B',
    size: 45,
  },
};

export const UNIT_ORDER: UnitId[] = ['Small', 'Speed', 'Shooter', 'Tank', 'King'];
